# Generated by Django 5.0.4 on 2024-04-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
